// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResolutteAudioAPI.Data;

namespace ResolutteAudioAPI.Migrations
{
    [DbContext(typeof(ResolutteAudioAPIContext))]
    [Migration("20220406162327_InitialMigrationMySql")]
    partial class InitialMigrationMySql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ResolutteAudioAPI.Models.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ArquivoNome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OperadorNome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("TipoLigacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Audio");
                });
#pragma warning restore 612, 618
        }
    }
}
